version: '3.8'
services:
  consul:
    image: hashicorp/consul:1.16
    container_name: consul
    restart: 'unless-stopped'
    ports:
      - '8500:8500'
    command: 'agent -dev -client=0.0.0.0'
    networks:
      - mebike-network

  auth-db:
    image: postgres:16-alpine
    container_name: auth-db
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - '5433:5432'
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - mebike-network

  user-db:
    image: postgres:16-alpine
    container_name: user-db
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    ports:
      - '5434:5432'
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - mebike-network

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: 'unless-stopped'
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    env_file:
      - ./.env
    depends_on:
      - api-gateway
    networks:
      - mebike-network

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: api-gateway
    restart: 'unless-stopped'
    depends_on:
      - consul
      - auth-service
      - user-service
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    env_file:
      - ./apps/api-gateway/.env
    networks:
      - mebike-network

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    container_name: auth-service
    restart: 'unless-stopped'
    depends_on:
      - consul
      - auth-db
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@auth-db:5432/${AUTH_DB_NAME}?schema=public
      - AUTH_SERVICE_PORT=50051
    networks:
      - mebike-network

  user-service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
    container_name: user-service
    restart: 'unless-stopped'
    depends_on:
      - consul
      - user-db
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@user-db:5432/${USER_DB_NAME}?schema=public
      - USER_SERVICE_PORT=50052
    networks:
      - mebike-network

networks:
  mebike-network:
    driver: bridge

volumes:
  auth_data:
  user_data:
