services:
  consul: 
    image: hashicorp/consul:1.16
    container_name: consul
    restart: "unless-stopped"
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - mebike-network
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: truongdz002 
      POSTGRES_DB: auth-db
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - mebike-network
  user-db:
    image: postgres:16-alpine
    container_name: user-db
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: truongdz002 
      POSTGRES_DB: user-db
    ports:
      - "5434:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - mebike-network
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: "unless-stopped"
    ports:
      - "80:80"   
      # - "443:443" 
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      # - ./nginx/ssl:/etc/nginx/ssl
    env_file:
      - ./.env
    depends_on:
      - api-gateway
    networks:
      - mebike-network
  api-gateway:
    build: 
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: api-gateway
    restart: "unless-stopped"
    depends_on:
      - consul
      - auth-service
      - user-service
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    env_file:
      - ./apps/api-gateway/.env
    networks:
      - mebike-network
  auth-service:
    build: 
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    container_name: auth-service
    restart: "unless-stopped"
    depends_on:
      - consul
      - auth-db
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    env_file:
      - ./apps/auth-service/.env
    networks:
      - mebike-network
  user-service:
    build: 
      context: .
      dockerfile: ./apps/user-service/Dockerfile
    container_name: user-service
    restart: "unless-stopped"
    depends_on:
      - consul
      - user-db
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    env_file:
      - ./apps/user-service/.env
    networks:
      - mebike-network

networks:
  mebike-network:
    driver: bridge
volumes:
  auth_data:
  user_data: